In [1]:
from google.cloud import bigquery

In [2]:
# Crea objeto cliente
client = bigquery.Client()

In [3]:
#Referencia al dataset 
dataset_ref = client.dataset("ncaa_basketball", project="bigquery-public-data")

# Llamada de API
dataset = client.get_dataset(dataset_ref)

In [4]:
tables = list(client.list_tables(dataset))

# Improme el nombre de todas las tablas dentro del dataset, en este caso con 10
for table in tables:  
    print(table.table_id)

mascots
mbb_games_sr
mbb_historical_teams_games
mbb_historical_teams_seasons
mbb_historical_tournament_games
mbb_pbp_sr
mbb_players_games_sr
mbb_teams
mbb_teams_games_sr
team_colors

In [5]:
#Referencia para llamar la tabla mascotas y su API
table_ref = dataset_ref.table("mascots")

table = client.get_table(table_ref)

In [6]:
# Imprime el esquema de la tabla mascota
table.schema

[SchemaField('id', 'STRING', 'NULLABLE', 'University unique ID from Sportradar', (), None),
 SchemaField('market', 'STRING', 'NULLABLE', 'The university to which the mascot belongs', (), None),
 SchemaField('name', 'STRING', 'NULLABLE', 'The name of the universityâ€™s team', (), None),
 SchemaField('mascot', 'STRING', 'NULLABLE', "The name of the university's mascot", (), None),
 SchemaField('mascot_name', 'STRING', 'NULLABLE', "The proper name of the university's mascot, if available (e.g. a character)", (), None),
 SchemaField('mascot_common_name', 'STRING', 'NULLABLE', 'The type of being or creature that the mascot embodies', (), None),
 SchemaField('tax_subspecies', 'STRING', 'NULLABLE', 'The subspecies to which the mascot belongs', (), None),
 SchemaField('tax_species', 'STRING', 'NULLABLE', 'The species to which the mascot belongs', (), None),
 SchemaField('tax_genus', 'STRING', 'NULLABLE', 'The genus to which the mascot belongs', (), None),
 SchemaField('tax_family', 'STRING', 'NULLABLE', 'The family to which the mascot belongs', (), None),
 SchemaField('tax_order', 'STRING', 'NULLABLE', 'The order to which the mascot belongs', (), None),
 SchemaField('tax_class', 'STRING', 'NULLABLE', 'The class to which the mascot belongs', (), None),
 SchemaField('tax_phylum', 'STRING', 'NULLABLE', 'The phylum to which the mascot belongs', (), None),
 SchemaField('tax_kingdom', 'STRING', 'NULLABLE', 'The kingdom to which the mascot belongs', (), None),
 SchemaField('tax_domain', 'STRING', 'NULLABLE', 'The domain to which the mascot belongs', (), None),
 SchemaField('non_tax_type', 'STRING', 'NULLABLE', 'The non-Linnean type of being or creature to which the mascot belongs, if applicable', (), None)]

In [10]:
# Prevista de la tabla
client.list_rows(table, max_results=5).to_dataframe()

/opt/conda/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Cannot use bqstorage_client if max_results is set, reverting to fetching data with the tabledata.list endpoint.

,id,market,name,mascot,mascot_name,mascot_common_name,tax_subspecies,tax_species,tax_genus,tax_family,tax_order,tax_class,tax_phylum,tax_kingdom,tax_domain,non_tax_type
0,2959bd24-7007-41ae-a3a3-abdf26888cfc,Tulsa,Golden Hurricane,Hurricane,Captain Cane,None,None,None,None,None,None,None,None,None,None,Weather
1,ad4bc983-8d2e-4e6f-a8f9-80840a786c64,Arizona State,Sun Devils,Devil,Sparky,None,None,None,None,None,None,None,None,None,None,Devils
2,f2d01b77-0f5d-4574-9e49-2a3eaf822e44,Drexel,Dragons,Dragon,Mario the Magnificent,None,None,None,None,None,None,None,None,None,None,Dragons
3,b47d10b8-a2a5-47df-a2f9-7bd0b9d51beb,Bradley,Braves,Gargoyle,Kaboom!,None,None,None,None,None,None,None,None,None,None,None
4,0113eea0-c943-4fff-9780-ae0fb099e7ef,Canisius,Golden Griffins,Griffin,Petey,None,None,None,None,None,None,None,None,None,None,Griffins

In [14]:
# Prevista de la tabla
client.list_rows(table, selected_fields=table.schema[:20], max_results=5).to_dataframe()

/opt/conda/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Cannot use bqstorage_client if max_results is set, reverting to fetching data with the tabledata.list endpoint.

,id,market,name,mascot,mascot_name,mascot_common_name,tax_subspecies,tax_species,tax_genus,tax_family,tax_order,tax_class,tax_phylum,tax_kingdom,tax_domain,non_tax_type
0,2959bd24-7007-41ae-a3a3-abdf26888cfc,Tulsa,Golden Hurricane,Hurricane,Captain Cane,None,None,None,None,None,None,None,None,None,None,Weather
1,ad4bc983-8d2e-4e6f-a8f9-80840a786c64,Arizona State,Sun Devils,Devil,Sparky,None,None,None,None,None,None,None,None,None,None,Devils
2,f2d01b77-0f5d-4574-9e49-2a3eaf822e44,Drexel,Dragons,Dragon,Mario the Magnificent,None,None,None,None,None,None,None,None,None,None,Dragons
3,b47d10b8-a2a5-47df-a2f9-7bd0b9d51beb,Bradley,Braves,Gargoyle,Kaboom!,None,None,None,None,None,None,None,None,None,None,None
4,0113eea0-c943-4fff-9780-ae0fb099e7ef,Canisius,Golden Griffins,Griffin,Petey,None,None,None,None,None,None,None,None,None,None,Griffins